# Generated by Django 4.2.7 on 2026-04-29 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supervisorprofile',
            options={'verbose_name': 'Amaliyot rahbar profili'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Talaba'), ('company_hr', 'Korxona HR'), ('mentor', 'Mentor'), ('supervisor', 'Amaliyot Rahbar'), ('dekanat', 'Dekanat'), ('kafedra', 'Kafedra'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.CreateModel(
            name='KafedraProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kafedra_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kafedra profili',
            },
        ),
    ]
