# Generated by Django 6.0.4 on 2026-04-17 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('hr_approved', 'HR tasdiqladi'), ('hr_rejected', 'HR rad etdi'), ('sup_approved', 'Ilmiy rahbar tasdiqladi'), ('sup_rejected', 'Ilmiy rahbar rad etdi'), ('completed', 'Yakunlandi')], default='pending', max_length=20)),
                ('hr_note', models.TextField(blank=True)),
                ('sup_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hr_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_reviewed_apps', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('sup_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sup_reviewed_apps', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='companies.vacancy')),
            ],
            options={
                'verbose_name': 'Ariza',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'vacancy')},
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('active', 'Faol'), ('completed', 'Yakunlangan')], default='pending', max_length=20)),
                ('mentor_grade', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('supervisor_grade', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('final_grade_letter', models.CharField(blank=True, max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internship', to='internships.application')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='companies.company')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internships', to='companies.mentor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_internships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Amaliyot',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('done', 'Bajarildi'), ('approved', 'Tasdiqlandi')], default='pending', max_length=20)),
                ('student_note', models.TextField(blank=True)),
                ('mentor_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='internships.internship')),
            ],
            options={
                'verbose_name': 'Vazifa',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator_type', models.CharField(choices=[('mentor', 'Mentor'), ('supervisor', 'Ilmiy Rahbar')], max_length=20)),
                ('grade', models.DecimalField(decimal_places=1, max_digits=4)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='internships.internship')),
            ],
            options={
                'verbose_name': 'Baholash',
                'unique_together': {('internship', 'evaluator_type')},
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('hours_worked', models.DecimalField(decimal_places=1, default=8, max_digits=4)),
                ('is_auto', models.BooleanField(default=False)),
                ('approved_by_mentor', models.BooleanField(default=False)),
                ('mentor_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='internships.internship')),
            ],
            options={
                'verbose_name': 'Kundalik',
                'ordering': ['-date'],
                'unique_together': {('internship', 'date')},
            },
        ),
    ]
