# Generated by Django 4.2.7 on 2026-04-29 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='kafedra_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='kafedra_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kafedra_reviewed_apps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='approved_by_kafedra',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='approved_by_supervisor',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='kafedra_log_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='supervisor_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('hr_approved', 'HR tasdiqladi'), ('hr_rejected', 'HR rad etdi'), ('sup_approved', 'Rahbar tasdiqladi'), ('sup_rejected', 'Rahbar rad etdi'), ('kafedra_approved', 'Kafedra tasdiqladi'), ('kafedra_rejected', 'Kafedra rad etdi'), ('dekan_approved', 'Dekanat tasdiqladi'), ('completed', 'Yakunlandi')], default='pending', max_length=20),
        ),
    ]
