# Generated by Django 4.2.7 on 2026-04-29 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internships', '0002_application_kafedra_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLogBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='logbooks/')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('pending', 'HR tasdiqlashi kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='draft', max_length=20)),
                ('total_logs', models.IntegerField(default=0)),
                ('total_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('hr_approved_at', models.DateTimeField(blank=True, null=True)),
                ('hr_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hr_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_logbooks', to=settings.AUTH_USER_MODEL)),
                ('internship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logbook', to='internships.internship')),
            ],
            options={
                'verbose_name': 'Kundalik daftar',
            },
        ),
    ]
