# Generated by Django 4.2.7 on 2026-04-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='reject_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('dekan_approved', 'Dekanat tasdiqladi'), ('sent', 'Korxonaga yuborildi'), ('company_accepted', 'Korxona qabul qildi'), ('rejected', 'Rad etildi')], default='draft', max_length=20),
        ),
    ]
