# Generated by Django 4.2.7 on 2026-05-01 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internships', '0004_application_assigned_supervisor'),
        ('companies', '0001_initial'),
        ('documents', '0002_document_accepted_at_document_reject_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='buyruqlar/')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('sent', 'Universitetga yuborildi')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='companies.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_orders', to='internships.internship')),
            ],
            options={
                'verbose_name': "Korxona buyrug'i",
                'ordering': ['-created_at'],
            },
        ),
    ]
