# Generated by Django 6.0.4 on 2026-04-17 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('submitted', 'Yuborildi'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='draft', max_length=20)),
                ('grade', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('reviewer_comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('internship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='internships.internship')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hisobot',
                'ordering': ['-created_at'],
            },
        ),
    ]
