# Generated by Django 4.2.7 on 2026-04-29 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='kafedra_approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='kafedra_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='kafedra_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='kafedra_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kafedra_reviewed_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
